import { Story, Clip, Rundown, RundownEntry } from '../types/newsforge';

const now = new Date().toISOString();
const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();

export const MOCK_STORIES: Story[] = [
  {
    id: 'STY-20250610-001',
    title: 'CM Press Conference',
    slug: 'cm-press-conf',
    category: 'Politics',
    format: 'VO+BITE',
    location: 'Bengaluru',
    date: '2025-06-10',
    source: 'Reporter Hub',
    content: 'Chief Minister to address key issues regarding the new infrastructure bill.',
    anchorScript: 'The Chief Minister has just concluded a high-stakes press conference in Bengaluru.',
    voiceoverScript: 'Visuals show the CM arriving at Vidhana Soudha and speaking to reporters.',
    notes: 'Urgent coverage requested.',
    priority: 'urgent',
    status: 'SUBMITTED',
    createdBy: 'Admin',
    assignedTo: null,
    createdAt: yesterday,
    updatedAt: now,
    editedScript: '',
    scriptEditedBy: null,
    scriptEditedAt: null,
    isScriptEdited: false,
  },
  {
    id: 'STY-20250610-002',
    title: 'ದಕ್ಷಿಣ ಕನ್ನಡ ಪ್ರವಾಹ',
    slug: 'dk-floods-update',
    category: 'National',
    format: 'PKG',
    location: 'Mangaluru',
    date: '2025-06-10',
    source: 'Stringer',
    content: 'Continuous rainfall leads to flooding in several parts of Dakshina Kannada.',
    anchorScript: '',
    voiceoverScript: '',
    notes: 'Keep updating visuals.',
    priority: 'breaking',
    status: 'EDITING',
    createdBy: 'Reporter1',
    assignedTo: 'Rahul M',
    createdAt: yesterday,
    updatedAt: now,
    editedScript: '',
    scriptEditedBy: null,
    scriptEditedAt: null,
    isScriptEdited: false,
  },
  {
    id: 'STY-20250610-003',
    title: 'Budget Session Day 3',
    slug: 'budget-session-d3',
    category: 'Politics',
    format: 'ANCHOR',
    location: 'New Delhi',
    date: '2025-06-10',
    source: 'Agency',
    content: 'Opposition raises questions on the education budget allocation.',
    anchorScript: 'Day 3 of the budget session saw heated debates in the assembly.',
    voiceoverScript: '',
    notes: 'Link with previous session clips.',
    priority: 'normal',
    status: 'READY',
    createdBy: 'Producer1',
    assignedTo: null,
    createdAt: yesterday,
    updatedAt: now,
    editedScript: '',
    scriptEditedBy: null,
    scriptEditedAt: null,
    isScriptEdited: false,
  },
  {
    id: 'STY-20250610-004',
    title: 'Cricket: KPL Finals',
    slug: 'kpl-finals',
    category: 'Sports',
    format: 'VO',
    location: 'Mysuru',
    date: '2025-06-10',
    source: 'Sports Desk',
    content: 'Final match scheduled between Mysuru Warriors and Hubli Tigers.',
    anchorScript: '',
    voiceoverScript: '',
    notes: 'Get match highlights.',
    priority: 'normal',
    status: 'DRAFT',
    createdBy: 'SportsReporter',
    assignedTo: null,
    createdAt: yesterday,
    updatedAt: now,
    editedScript: '',
    scriptEditedBy: null,
    scriptEditedAt: null,
    isScriptEdited: false,
  },
  {
    id: 'STY-20250610-005',
    title: 'ಕಬಡ್ಡಿ ಟೂರ್ನಿ ಫಲಿತಾಂಶ',
    slug: 'kabaddi-results',
    category: 'Sports',
    format: 'VO+BITE',
    location: 'Hubballi',
    date: '2025-06-10',
    source: 'Local Desk',
    content: 'Results of the state-level Kabaddi tournament held in Hubballi.',
    anchorScript: 'The state-level Kabaddi tournament has reached its conclusion.',
    voiceoverScript: '',
    notes: 'Include winner interview.',
    priority: 'normal',
    status: 'SUBMITTED',
    createdBy: 'Reporter2',
    assignedTo: 'Anita K',
    createdAt: now,
    updatedAt: now,
    editedScript: '',
    scriptEditedBy: null,
    scriptEditedAt: null,
    isScriptEdited: false,
  },
  // System-generated stories (created by "System")
  {
    id: 'SYS-HEADLINE-001',
    title: 'HEADLINES',
    slug: 'HEADLINES',
    category: 'System',
    format: 'ANCHOR',
    status: 'READY',
    location: 'Studio',
    date: '2025-06-10',
    source: 'System',
    content: '',
    anchorScript: 'Good evening, here are the top headlines for tonight...',
    voiceoverScript: '',
    notes: '',
    priority: 'normal',
    createdBy: 'SYSTEM',
    assignedTo: null,
    createdAt: yesterday,
    updatedAt: now,
    editedScript: '',
    scriptEditedBy: null,
    scriptEditedAt: null,
    isScriptEdited: false,
  },
  {
    id: 'SYS-START-001',
    title: 'START',
    slug: 'START',
    category: 'System',
    format: 'ANCHOR',
    status: 'READY',
    location: 'Studio',
    date: '2025-06-10',
    source: 'System',
    content: '',
    anchorScript: 'Welcome to the 9 PM Bulletin.',
    voiceoverScript: '',
    notes: '',
    priority: 'normal',
    createdBy: 'SYSTEM',
    assignedTo: null,
    createdAt: yesterday,
    updatedAt: now,
    editedScript: '',
    scriptEditedBy: null,
    scriptEditedAt: null,
    isScriptEdited: false,
  },
  {
    id: 'SYS-BREAK1-001',
    title: 'BREAK 1',
    slug: 'BREAK-1',
    category: 'System',
    format: 'BREAK',
    status: 'READY',
    location: 'None',
    date: '2025-06-10',
    source: 'System',
    content: '',
    anchorScript: '',
    voiceoverScript: '',
    notes: '',
    priority: 'normal',
    createdBy: 'SYSTEM',
    assignedTo: null,
    createdAt: yesterday,
    updatedAt: now,
    editedScript: '',
    scriptEditedBy: null,
    scriptEditedAt: null,
    isScriptEdited: false,
  },
  {
    id: 'SYS-END-001',
    title: 'END',
    slug: 'END',
    category: 'System',
    format: 'ANCHOR',
    status: 'READY',
    location: 'Studio',
    date: '2025-06-10',
    source: 'System',
    content: '',
    anchorScript: 'Thank you for joining us tonight. Goodnight.',
    voiceoverScript: '',
    notes: '',
    priority: 'normal',
    createdBy: 'SYSTEM',
    assignedTo: null,
    createdAt: yesterday,
    updatedAt: now,
    editedScript: '',
    scriptEditedBy: null,
    scriptEditedAt: null,
    isScriptEdited: false,
  },
];

export const MOCK_CLIPS: Clip[] = [
  {
    id: 'STY-20250610-001-CLIP-01',
    storyId: 'STY-20250610-001',
    fileName: 'STY-20250610-001_C01_RAW.mp4',
    originalFileName: 'cm_arrival.mp4',
    fileUrl: null,
    displayLabel: null,
    status: 'RAW',
    editingInstructions: '',
    editorialNotes: '',
    claimedBy: null,
    duration: null,
    codec: 'H.264',
    resolution: '1080p',
    fileSize: '45MB',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'STY-20250610-001-CLIP-02',
    storyId: 'STY-20250610-001',
    fileName: 'STY-20250610-001_C02_RAW.mp4',
    originalFileName: 'cm_speech_raw.mp4',
    fileUrl: null,
    displayLabel: null,
    status: 'AVAILABLE',
    editingInstructions: '',
    editorialNotes: '',
    claimedBy: null,
    duration: null,
    codec: 'H.264',
    resolution: '1080p',
    fileSize: '120MB',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'STY-20250610-002-CLIP-01',
    storyId: 'STY-20250610-002',
    fileName: 'STY-20250610-002_C01_RAW.mp4',
    originalFileName: 'flood_mangalore.mp4',
    fileUrl: null,
    displayLabel: null,
    status: 'AVAILABLE',
    editingInstructions: 'Cut to 2:30, remove shaky opening',
    editorialNotes: 'High priority for bulletin.',
    claimedBy: null,
    duration: null,
    codec: 'ProRes',
    resolution: '1080i',
    fileSize: '2.4GB',
    createdAt: yesterday,
    updatedAt: now,
  },
  {
    id: 'STY-20250610-003-CLIP-01',
    storyId: 'STY-20250610-003',
    fileName: 'STY-20250610-003_C01_RAW.mp4',
    originalFileName: 'budget_d3_final.mp4',
    fileUrl: null,
    displayLabel: 'BUDGET_PKG',
    status: 'COMPLETED',
    editingInstructions: 'Final package.',
    editorialNotes: 'Clean audio.',
    claimedBy: 'Rahul M',
    duration: '03:15',
    codec: 'H.264',
    resolution: '1080p',
    fileSize: '250MB',
    createdAt: yesterday,
    updatedAt: now,
  },
  {
    id: 'STY-20250610-005-CLIP-01',
    storyId: 'STY-20250610-005',
    fileName: 'STY-20250610-005_C01_RAW.mp4',
    originalFileName: 'kabaddi_winner.mp4',
    fileUrl: null,
    displayLabel: null,
    status: 'IN_PROCESS',
    editingInstructions: 'Trim bits of crowd noise.',
    editorialNotes: 'Interview with captain.',
    claimedBy: 'Anita K',
    duration: '01:20',
    codec: 'H.264',
    resolution: '1080p',
    fileSize: '85MB',
    createdAt: now,
    updatedAt: now,
  },
];

export const MOCK_RUNDOWNS: Rundown[] = [
  {
    id: 'RD-20250610-001',
    title: '9:00 PM Bulletin',
    airDate: '2025-06-10',
    airTime: '21:00:00',
    plannedDuration: '00:30:00',
    status: 'READY',
    headline: "ಸಂಜೆ 9 ಸುದ್ದಿ",
    startTime: "21:00:00",
    endTime: "21:30:00",
    break1After: 3,
    break1Duration: "03:00",
    break2After: 6,
    break2Duration: "02:30",
    entries: [
      {
        id: 'RE-1',
        rundownId: 'RD-20250610-001',
        storyId: 'SYS-HEADLINE-001',
        orderIndex: 0,
        overrideDuration: '00:00:30',
        entryStatus: 'PENDING',
        notes: '',
      },
      {
        id: 'RE-2',
        rundownId: 'RD-20250610-001',
        storyId: 'SYS-START-001',
        orderIndex: 1,
        overrideDuration: '00:00:15',
        entryStatus: 'PENDING',
        notes: '',
      },
      {
        id: 'RE-3',
        rundownId: 'RD-20250610-001',
        storyId: 'STY-20250610-002',
        orderIndex: 2,
        overrideDuration: '00:03:00',
        entryStatus: 'PENDING',
        notes: '',
      },
      {
        id: 'RE-4',
        rundownId: 'RD-20250610-001',
        storyId: 'SYS-BREAK1-001',
        orderIndex: 3,
        overrideDuration: '00:05:00',
        entryStatus: 'PENDING',
        notes: '',
      },
      {
        id: 'RE-5',
        rundownId: 'RD-20250610-001',
        storyId: 'STY-20250610-001',
        orderIndex: 4,
        overrideDuration: '00:02:30',
        entryStatus: 'PENDING',
        notes: '',
      },
      {
        id: 'RE-6',
        rundownId: 'RD-20250610-001',
        storyId: 'SYS-END-001',
        orderIndex: 5,
        overrideDuration: '00:00:15',
        entryStatus: 'PENDING',
        notes: '',
      },
    ],
  },
  {
    id: 'RD-20250610-002',
    title: '10:00 PM Bulletin',
    airDate: '2025-06-10',
    airTime: '22:00:00',
    plannedDuration: '00:30:00',
    status: 'PLANNING',
    headline: "ರಾತ್ರಿ 10 ಬುಲೆಟಿನ್",
    startTime: "22:00:00",
    endTime: "22:30:00",
    break1After: 4,
    break1Duration: "03:00",
    break2After: null,
    break2Duration: "",
    entries: [],
  },
];
